### ISSUE TITLE
Extend the date range

### ISSUE THREAD

**Issue by huaxialeee** [pournaki/twitter-explorer#10]
Hi, how to extend the date range to before 2012 Oct. 31? I'm using the academic account but find that the earliest date is 2012 Oct. 31. Thanks.

**Comment by pournaki** [comment]
Hi, thanks for pointing this out. By default, the date selector goes back 10 years only, I fixed it by adding the day Twitter was launched as the `min_date` (https://github.com/pournaki/twitter-explorer/commit/b3ec6191e9409d4d3e5cbe07b2da61499fad21b1).

**Comment by huaxialeee** [comment]
Hi Pournaki,

Thank you so much! Could you double-check the code since I believe the launch date is 2006/07/15 instead of 2016? Thanks.

**Comment by pournaki** [comment]
Oh no, my bad! It's fixed now: https://github.com/pournaki/twitter-explorer/commit/161b4d4bb2c7a075260eb4ca8d37debf0b9c6d5c
