### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by hamelena** [pournaki/twitter-explorer#2]
Hi,

I tried to install twitter-explorer as described in your Readme. Installation failed, following message:
`Cloning into 'testrepo-'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

Are there special permission rights required for the installation?

Thank you in advance

**Comment by pournaki** [comment]
Hi @hamelena,
sorry, I just realized the link is wrong. Here is the correct command: 
```
$ git clone https://github.com/pournaki/twitter-explorer.git
```
