### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by baldzuhnc** [pournaki/twitter-explorer#3]
Hey there and thank you for developing this beautiful tool. 

Recently I get these Error messages when trying to run the visualizer options (not just the timeline function). Is there a solution for that?

![Bildschirmfoto 2020-11-03 um 18 13 06](https://user-images.githubusercontent.com/73642778/98018174-84190e80-1e00-11eb-8ebc-c16c90557e33.png)

**Comment by pournaki** [comment]
hi @baldzuhnc, thanks for reaching out! 
at this time, I cannot reproduce the issue. could you give some more information about the error? does it occur only for that one dataset or also for previously working ones?

**Comment by baldzuhnc** [comment]
thank you for the fast reply! it didn't have these problems using version 0.3.0. However, the datasets i collected using v0.3.0 were always complete. With the new v0.3.1. i tried to gather bigger datasets but stopped the collection process after some time (during a sleeping phase) because i couldn't wait anymore haha. these datasets lead to the error message. complete datasets can be correctly visalized. sorry i should have clarified that earlier.

**Comment by pournaki** [comment]
okay, in this case there was an error when the collector wrote to the json file. this can happen when it is killed in the middle of writing. I therefore recommend only quitting the collector while it is sleeping or when it has collected all tweets. 

note however that you can run the visualizer while the collector is running! you can already start visualizing the dataset while the file is still being updated by the collector. 

as for your corrupted dataset, you can "save" it by finding the corrupted line: 

```
import json

with open("path/to/corrupted/dataset", "r", encoding="utf-8") as f:
    for idx, line in enumerate(f):
        try:
            json.loads(line)
        except json.JSONDecodeError:
            print(f"This line contains an error: {idx}")
```

and just deleting it with an editor of your choice.
